#!/bin/bash


#Arrays

myArray=(1 20 3.5 Hello "Hey Buddy!")


echo "All the elements in the array are ${myArray[*]}"

echo "third element in the array is ${myArray[2]}"

#How to find length of an array
echo "Length is an array ${#myArray[*]}"

#Slicing in array
echo "first three elements of the array are: ${myArray[*]:3:*}"




